### ISSUE TITLE
Your README seems to be broken

### ISSUE THREAD

**Issue by IvanAlejandro888** [zmyaro/holo-web#13]
Hey, I can't trust in a CSS that has an ugly README. You should add some pictures in addition to the website.
It's the only thing.
Thanks

**Comment by zmyaro** [comment]
I am not planning to update Holo Web anymore since Google deprecated Holo Design in 2014, so I might revise the readme (or look over a pull request if you want to submit one) if I have a spare minute, but I do not want to promise anything.  Thanks for your interest in Holo Web, and I am sorry I do not have the time to give this project more attention.

**Comment by IvanAlejandro888** [comment]
Yes, it's deprecated, but anyway, is very cool. I sometimes miss Holo and want to back to it, but I prefer Material for my apps.
But, great project.

Zachary Yaro <notifications@github.com> wrote:



I am not planning to update Holo Web anymore since Google deprecated Holo Design in 2014, so I might revise the readme (or look over a pull request if you want to submit one) if I have a spare minute, but I do not want to promise anything. Thanks for your interest in Holo Web, and I am sorry I do not have the time to give this project more attention.

**Comment by zmyaro** [comment]
I also miss some aspects of Holo, and I am glad you are finding Holo Web useful.  Unfortunately, as I said, I doubt I will have time to update this project much in the near future, so the only visual examples of Holo Web will continue to be the ones at https://holo.zmyaro.com.
